repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: main
    hooks:
      - id: prettier
        args: [--write, '**/*.{js,jsx,ts,tsx,css,html,json,md}']
  - repo: https://github.com/psf/autopep8
    rev: main
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive, '**/*.py']