from enum import Enum


class HeuristicType(Enum):
    PATH_CHEAPEST_ARC = 'PATH_CHEAPEST_ARC'
    PATH_MOST_CONSTRAINED_ARC = 'PATH_MOST_CONSTRAINED_ARC'
    EVALUATOR_STRATEGY = 'EVALUATOR_STRATEGY'
    SAVINGS = 'SAVINGS'
    SWEEP = 'SWEEP'
    CHRISTOFIDES = 'CHRISTOFIDES'
    ALL_UNPERFORMED = 'ALL_UNPERFORMED'
    BEST_INSERTION = 'BEST_INSERTION'
    PARALLEL_CHEAPEST_INSERTION = 'PARALLEL_CHEAPEST_INSERTION'
    SEQUENTIAL_CHEAPEST_INSERTION = 'SEQUENTIAL_CHEAPEST_INSERTION'
    LOCAL_CHEAPEST_INSERTION = 'LOCAL_CHEAPEST_INSERTION'
    LOCAL_CHEAPEST_COST_INSERTION = 'LOCAL_CHEAPEST_COST_INSERTION'
    GLOBAL_CHEAPEST_ARC = 'GLOBAL_CHEAPEST_ARC'
    LOCAL_CHEAPEST_ARC = 'LOCAL_CHEAPEST_ARC'
    FIRST_UNBOUND_MIN_VALUE = 'FIRST_UNBOUND_MIN_VALUE'


class MetaheuristicType(Enum):
    GREEDY_DESCENT = 'GREEDY_DESCENT'
    GUIDED_LOCAL_SEARCH = 'GUIDED_LOCAL_SEARCH'
    SIMULATED_ANNEALING = 'SIMULATED_ANNEALING'
    TABU_SEARCH = 'TABU_SEARCH'
    GENERIC_TABU_SEARCH = 'GENERIC_TABU_SEARCH'
